spring.datasource.url=jdbc:postgresql://db:5432/resurs
spring.datasource.username=resurs
spring.datasource.password=resurs123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
company-validation.client=mock


scoring.initialScore=100

scoring.solidity.minimum=0.20
scoring.solidity.low =0.25
scoring.solidity.flag_below_branch_avg=0.75

scoring.liquidity.minimum=1.0
scoring.liquidity.low=1.2
scoring.liquidity.good=2.0

scoring.debtRatio.maximum=3.0
scoring.debtRatio.high=2.0

scoring.operatingMargin.low=0.02
scoring.operatingMargin.good=0.10
scoring.operatingMargin.flag_below_branch_avg=0.5

scoring.credit.high_credit_solidity=1000000
scoring.credit.extreme_credit=5000000

scoring.turnover.low = 500000

scoring.cashflowratio.low=0.08
scoring.cashflowratio.very_low=0.05

scoring.investmentCashFlow.inverse_cashflow_flag=0.3

scoring.interestCoverage.reject = 1.5
scoring.interestCoverage.low = 2.5

scoring.equityCoverage.credit_quotient=0.3

scoring.debtAckError.high=2.0

scoring.finalScoreThresholds.flag_review=80
scoring.finalScoreThresholds.manual_review=75
scoring.finalScoreThresholds.reject=50
